- name: demo loop
  hosts: localhost
  connection: local
  tasks: 
    - name: fruits name
      ansible.builtin.debug:
        msg: fruit name - {{ item }}
      when: what == {{ item }}
      loop:
        - apple
        - orange
        - banana
        - grape
      
