- name: demo loop
  hosts: localhost
  connection: local
  tasks: 
    - name: fruits name
      ansible.builtin.debug:
        msg: fruit name - {{ item }}
      loop:
        - apple
        - orange
        - banana
        - grape
    - name: fruits and quantity
      ansible.builtin.debug:
        msg:
      loop:
        - { fruits name: apple, quantity: 100 }
        - { fruits name: orange, quantity: 200 }
        - { fruits name: banana, quantity: 300 }
        - { fruits name: grape, quantity: 500 }
