- name: demo loop
  hosts: localhost
  connection: local
  tasks: 
    - name: fruits name
      ansible.builtin.debug:
        msg: fruit name - {{ item }}
      loop:
        - apple
        - orange
        - banana
        - grape
    - name: fruits and quantity
      ansible.builtin.debug:
        msg: Fruit name - {{ item.name}}, Quantity - {{ item.quantity }}
      loop:
        - { name: apple, quantity: 100 }
        - { name: orange, quantity: 200 }
        - { name: banana, quantity: 300 }
        - { name: grape, quantity: 500 }
